name: "Deploy backend and frontend workflow"

on:
  workflow_dispatch:

permissions:
  id-token: write
  contents: read

jobs:
  deploy_backend_infra:
    runs-on: ubuntu-latest
    name: "Deploy backend - Bicep"
    steps:
      - name: "Checkout"
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_AD_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_AD_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}

      - name: bicep-build - Key vault
        uses: Azure/bicep-build-action@v1.0.0
        with:
          bicepFilePath: ./src/Bicep/vaults/deploy.bicep
          outputFilePath: ./src/Bicep/vaults/azuredeploy.json

      - name: bicep-build - Storage Account
        uses: Azure/bicep-build-action@v1.0.0
        with:
          bicepFilePath: ./src/Bicep/storageAccounts/deploy.bicep
          outputFilePath: ./src/Bicep/storageAccounts/azuredeploy.json

      - name: "ARM - TTK module install and test modules"
        id: arm-ttk
        shell: pwsh
        run: |
          write-output ">>>> Installing ARM_TTK module"
          Invoke-WebRequest -Uri "https://github.com/Azure/arm-ttk/releases/download/20220121/arm-ttk.2022.01.21.zip" -OutFile "arm-ttk.2022.01.21.zip"
          Expand-Archive .\arm-ttk.2022.01.21.zip
          Import-Module ./arm-ttk.2022.01.21/arm-ttk/arm-ttk.psd1 -Force
          write-output ">>>> arm-ttk  Key vault analysis"
          Test-AzTemplate -TemplatePath ./src/Bicep/vaults/azuredeploy.json -ErrorAction continue
          write-output ">>>> arm-ttk  storageAccounts analysis"
          Test-AzTemplate -TemplatePath ./src/Bicep/storageAccounts/azuredeploy.json -ErrorAction continue

      - name: SNYK - Run Snyk to check key vault ARM template file for issues
        continue-on-error: true
        uses: snyk/actions/iac@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          file: ./src/Bicep/vaults/azuredeploy.json
      - name: SNYK - Run Snyk to check storageAccounts template file for issues
        continue-on-error: true
        uses: snyk/actions/iac@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          file: ./src/Bicep/storageAccounts/azuredeploy.json

      - name: Upload result to GitHub Code Scanning
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: snyk.sarif

      - name: Deploy Key Vault
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          resourceGroupName: "netcoreconf-demo"
          template: ./src/Bicep/vaults/deploy.bicep
          failOnStdErr: false

      - name: Deploy Storage Account
        uses: azure/arm-deploy@v1
        with:
          subscriptionId: ${{ secrets.ARM_SUBSCRIPTION_ID }}
          resourceGroupName: "netcoreconf-demo"
          template: ./src/Bicep/storageAccounts/deploy.bicep
          failOnStdErr: false

  deploy_frontend_infra:
    name: "Deploy frontend - TF"
    needs: deploy_backend_infra
    uses: joselcaguilar/HardeningIaC/.github/workflows/terraform-platform.yml@main
    secrets:
      AZURE_AD_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      AZURE_AD_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
