name: "TF test Workflow"

on:
  workflow_dispatch:
  push:
    branches: [main, users/**]
    paths:
    - "src/Terraform/**"

env:
  tflintRulesExcluded: ""
  tfLintAzureRulesVersion: v0.14.0
  tfLintVersion: v0.34.1
  tfsecVersion: v1.1.5

jobs:
  build_source_code_dev:
    environment: "Dev"
    runs-on: ubuntu-latest
    name: "Test and deploy infra"
    steps:
      - uses: actions/checkout@v2
      - name: tflint
        id: tflint-execution
        continue-on-error: true
        working-directory: ${{ github.workspace }}/src/Terraform/key-vault
        run: |
            tfLintRulesExcluded=`for i in $(echo ${{ env.tflintRulesExcluded }} | sed "s/,/ /g"); do echo "--disable-rule=$i"; done`
  
            echo tflint --module --loglevel=debug $tfLintRulesExcluded
            echo 'plugin "azurerm" {' >.tflint.hcl
            echo '  enabled = true' >>.tflint.hcl
            echo '}' >>.tflint.hcl
            mkdir -p .tflint.d/plugins
            cd .tflint.d/plugins
            
            curl -L "https://github.com/terraform-linters/tflint-ruleset-azurerm/releases/download/${{ env.tfLintAzureRulesVersion }}/tflint-ruleset-azurerm_linux_amd64.zip" -o tflint-AzRuleset.zip
            unzip tflint-AzRuleset.zip
            rm tflint-AzRuleset.zip
            chmod +x tflint-ruleset-azurerm
  
            docker run --rm -v "${{ github.workspace }}/src/Terraform:/data" -w="/data/key-vault" -t ghcr.io/terraform-linters/tflint:${{ env.tfLintVersion }} -f sarif --module --loglevel=debug $tfLintRulesExcluded > ${{ github.workspace }}/src/Terraform/key-vault/tflint-key-vault.sarif

      - name: tfsec
        id: tfsec-execution
        continue-on-error: true
        run: |
          docker run --rm -v "${{ github.workspace }}/src/Terraform:/src" aquasec/tfsec:${{ env.tfsecVersion }}  --format sarif /src/key-vault > ${{ github.workspace }}/src/Terraform/key-vault/tfsec-key-vault.sarif 

      - name: Upload tflint SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ./src/Terraform/key-vault/tflint-key-vault.sarif

      - name: Upload tfsec SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ./src/Terraform/key-vault/tfsec-key-vault.sarif

      - name: Invalid value/syntax
        if: steps.tflint-execution.outcome != 'success'
        run: echo 'Deployment to prod is forbidden, fix the value/syntax provided'

      - name: There are vulnerabilities
        if: steps.tfsec-execution.outcome != 'success'
        run: echo 'Deployment to prod is forbidden, vulnerabilities found'