name: "TF Template Workflow"

on:
  workflow_call:
  workflow_dispatch:

env:
  tflintRulesExcluded: ""
  tfLintAzureRulesVersion: v0.14.0
  tfLintVersion: v0.34.1
  tfsecVersion: v1.1.5

jobs:
  deploy_frontend_infra:
    runs-on: ubuntu-latest
    env:
      ARM_CLIENT_ID: ${{ secrets.AZURE_AD_CLIENT_ID }}
      ARM_CLIENT_SECRET: ${{ secrets.AZURE_AD_CLIENT_SECRET }}
      ARM_SUBSCRIPTION_ID: ${{ secrets.ARM_SUBSCRIPTION_ID }}
      ARM_TENANT_ID: ${{ secrets.AZURE_AD_TENANT_ID }}
    steps:
      - uses: actions/checkout@v2
      - name: tflint acr
        id: tflint-execution
        continue-on-error: true
        working-directory: ${{ github.workspace }}/src/Terraform/container-registry
        run: |
            tfLintRulesExcluded=`for i in $(echo ${{ env.tflintRulesExcluded }} | sed "s/,/ /g"); do echo "--disable-rule=$i"; done`
  
            echo tflint --module -f sarif $tfLintRulesExcluded
            echo 'plugin "azurerm" {' >.tflint.hcl
            echo '  enabled = true' >>.tflint.hcl
            echo '}' >>.tflint.hcl
            mkdir -p .tflint.d/plugins
            cd .tflint.d/plugins
            
            curl -L "https://github.com/terraform-linters/tflint-ruleset-azurerm/releases/download/${{ env.tfLintAzureRulesVersion }}/tflint-ruleset-azurerm_linux_amd64.zip" -o tflint-AzRuleset.zip
            unzip tflint-AzRuleset.zip
            rm tflint-AzRuleset.zip
            chmod +x tflint-ruleset-azurerm
  
            docker run --rm -v "${{ github.workspace }}/src/Terraform:/data" -w="/data/container-registry" -t ghcr.io/terraform-linters/tflint:${{ env.tfLintVersion }} -f sarif --module $tfLintRulesExcluded > ${{ github.workspace }}/src/Terraform/container-registry/tflint-container-registry.sarif

      - name: tfsec acr
        id: tfsec-execution
        continue-on-error: true
        run: |
          docker run --rm -v "${{ github.workspace }}/src/Terraform:/src" aquasec/tfsec:${{ env.tfsecVersion }}  --format sarif /src/container-registry > ${{ github.workspace }}/src/Terraform/container-registry/tfsec-container-registry.sarif

      - name: Upload tflint SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ./src/Terraform/container-registry/tflint-container-registry.sarif

      - name: Upload tfsec SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ./src/Terraform/container-registry/tfsec-container-registry.sarif

      - name: ACR TF Deployment
        if: steps.tflint-execution.outcome == 'success' && steps.tfsec-execution.outcome == 'success'
        working-directory: ./src/Terraform/container-registry
        run: |
          terraform init
          terraform validate
          terraform plan -out tfplan
          terraform apply --auto-approve tfplan
