name: "TF Template Workflow"

on:
  workflow_call:
    secrets:
      AZURE_AD_CLIENT_ID:
        required: true
      AZURE_AD_TENANT_ID:
        required: true
      ARM_SUBSCRIPTION_ID:
        required: true
  workflow_dispatch:

permissions:
  id-token: write
  contents: read
  security-events: write

env:
  tflintRulesExcluded: ""
  tfLintAzureRulesVersion: v0.23.0
  tfLintVersion: v0.46.1
  tfsecVersion: v1.28.1
  imageName: netcoreconf23ml

jobs:
  check_acr_vulns:
    name: Container Registry assessment
    runs-on: ubuntu-latest
    outputs:
      tfsecOutcome: ${{ steps.tfsec-execution-acr.outcome }}
      tflintOutcome: ${{ steps.tflint-execution-acr.outcome }}

    steps:
      - uses: actions/checkout@v2
      - name: tflint acr
        id: tflint-execution-acr
        continue-on-error: true
        working-directory: ${{ github.workspace }}/src/Terraform/container-registry
        run: |
          tfLintRulesExcluded=`for i in $(echo ${{ env.tflintRulesExcluded }} | sed "s/,/ /g"); do echo "--disable-rule=$i"; done`

          echo tflint --module -f sarif $tfLintRulesExcluded
          echo 'plugin "azurerm" {' >.tflint.hcl
          echo '  enabled = true' >>.tflint.hcl
          echo '}' >>.tflint.hcl
          mkdir -p .tflint.d/plugins
          cd .tflint.d/plugins

          curl -L "https://github.com/terraform-linters/tflint-ruleset-azurerm/releases/download/${{ env.tfLintAzureRulesVersion }}/tflint-ruleset-azurerm_linux_amd64.zip" -o tflint-AzRuleset.zip
          unzip tflint-AzRuleset.zip
          rm tflint-AzRuleset.zip
          chmod +x tflint-ruleset-azurerm

          docker run --rm -v "${{ github.workspace }}/src/Terraform:/data" -w="/data/container-registry" -t ghcr.io/terraform-linters/tflint:${{ env.tfLintVersion }} -f sarif --module $tfLintRulesExcluded > ${{ github.workspace }}/src/Terraform/container-registry/tflint-container-registry.sarif

      - name: tfsec acr
        id: tfsec-execution-acr
        continue-on-error: true
        run: |
          docker run --rm -v "${{ github.workspace }}/src/Terraform:/src" aquasec/tfsec:${{ env.tfsecVersion }} --format sarif /src/container-registry > ${{ github.workspace }}/src/Terraform/container-registry/tfsec-container-registry.sarif

      - name: Upload tflint SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ./src/Terraform/container-registry/tflint-container-registry.sarif

      - name: Upload tfsec SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ./src/Terraform/container-registry/tfsec-container-registry.sarif

  check_aas_vulns:
    name: App Services assessment
    runs-on: ubuntu-latest
    outputs:
      tfsecOutcome: ${{ steps.tfsec-execution-aas.outcome }}
      tflintOutcome: ${{ steps.tflint-execution-aas.outcome }}

    steps:
      - uses: actions/checkout@v2
      - name: tflint app services
        id: tflint-execution-aas
        continue-on-error: true
        working-directory: ${{ github.workspace }}/src/Terraform/app-services
        run: |
          tfLintRulesExcluded=`for i in $(echo ${{ env.tflintRulesExcluded }} | sed "s/,/ /g"); do echo "--disable-rule=$i"; done`

          echo tflint --module -f sarif $tfLintRulesExcluded
          echo 'plugin "azurerm" {' >.tflint.hcl
          echo '  enabled = true' >>.tflint.hcl
          echo '}' >>.tflint.hcl
          mkdir -p .tflint.d/plugins
          cd .tflint.d/plugins

          curl -L "https://github.com/terraform-linters/tflint-ruleset-azurerm/releases/download/${{ env.tfLintAzureRulesVersion }}/tflint-ruleset-azurerm_linux_amd64.zip" -o tflint-AzRuleset.zip
          unzip tflint-AzRuleset.zip
          rm tflint-AzRuleset.zip
          chmod +x tflint-ruleset-azurerm

          docker run --rm -v "${{ github.workspace }}/src/Terraform:/data" -w="/data/app-services" -t ghcr.io/terraform-linters/tflint:${{ env.tfLintVersion }} -f sarif --module $tfLintRulesExcluded > ${{ github.workspace }}/src/Terraform/app-services/tflint-app-services.sarif

      - name: tfsec app services
        id: tfsec-execution-aas
        continue-on-error: true
        run: |
          docker run --rm -v "${{ github.workspace }}/src/Terraform:/src" aquasec/tfsec:${{ env.tfsecVersion }} --format sarif /src/app-services > ${{ github.workspace }}/src/Terraform/app-services/tfsec-app-services.sarif

      - name: Upload tflint aas SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ./src/Terraform/app-services/tflint-app-services.sarif

      - name: Upload tfsec aas SARIF file
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ./src/Terraform/app-services/tfsec-app-services.sarif

  deploy_frontend:
    name: Frontend deployment
    needs: [check_acr_vulns, check_aas_vulns]
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Azure Login
        uses: azure/login@v1
        with:
          client-id: ${{ secrets.AZURE_AD_CLIENT_ID }}
          tenant-id: ${{ secrets.AZURE_AD_TENANT_ID }}
          subscription-id: ${{ secrets.ARM_SUBSCRIPTION_ID }}

      - name: ACR TF Deployment
        if: needs.check_acr_vulns.outputs.tfsecOutcome == 'success' && needs.check_acr_vulns.outputs.tflintOutcome == 'success'
        working-directory: ./src/Terraform/container-registry
        run: |
          terraform init
          terraform validate
          terraform plan -out tfplan
          terraform apply --auto-approve tfplan
        env:
          ARM_CLIENT_ID: ${{ env.AZURE_AD_CLIENT_ID }}
          ARM_TENANT_ID: ${{ env.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ env.ARM_SUBSCRIPTION_ID }}
          ARM_USE_OIDC: true

      - name: Build docker Tensorflow model
        working-directory: ./src/Docker
        run: |
          docker build -t ${{ env.imageName }}:${{ github.run_number }} -f Dockerfile .
          docker tag "${{ env.imageName }}:${{ github.run_number }}" "netcoreconf23acr.azurecr.io/netcoreconf23acr/${{ env.imageName }}:latest"

      # Run analyzers
      - name: Run Microsoft Security DevOps Analysis
        uses: microsoft/security-devops-action@preview
        continue-on-error: true
        id: msdo
        with:
          tools: trivy

      # Upload alerts to the Security tab
      - name: Upload alerts to Security tab
        uses: github/codeql-action/upload-sarif@v2
        with:
          sarif_file: ${{ steps.msdo.outputs.sarifFile }}

      - name: Push Docker image
        run: |
          az acr login -n netcoreconf23acr
          docker push netcoreconf23acr.azurecr.io/netcoreconf23acr/${{ env.imageName }}:latest

      - name: App Services TF Deployment
        if: needs.check_aas_vulns.outputs.tfsecOutcome != 'success' && needs.check_aas_vulns.outputs.tflintOutcome == 'success' # skipping tfsec for demo purposes
        working-directory: ./src/Terraform/app-services
        run: |
          terraform init
          terraform validate
          terraform plan -out tfplan
          terraform apply --auto-approve tfplan
        env:
          ARM_CLIENT_ID: ${{ env.AZURE_AD_CLIENT_ID }}
          ARM_TENANT_ID: ${{ env.ARM_TENANT_ID }}
          ARM_SUBSCRIPTION_ID: ${{ env.ARM_SUBSCRIPTION_ID }}
          ARM_USE_OIDC: true
