name: "TF test Workflow"

on:
  workflow_dispatch:
  push:
    branches: [main, users/**]
    paths:
    - "src/Terraform/**"
jobs:
  build_source_code_dev:
    environment: "Dev"
    runs-on: ubuntu-latest
    name: "Test and deploy infra"
    steps:
      - uses: actions/checkout@v2
      - name: tfsec
        continue-on-error: true
        run: |
          docker run --rm -v "${{ github.workspace }}/src/Terraform:/src" aquasec/tfsec --format sarif /src/key-vault > ${{ github.workspace }}/src/Terraform/key-vault/tfsec-key-vault.sarif 

      - name: Upload SARIF file
        uses: github/codeql-action/upload-sarif@v1
        with:
          sarif_file: ./src/Terraform/key-vault/tfsec-key-vault.sarif