name: tf-pr-commenter
on:
  pull_request:

jobs:
  terraform:
    name: Terraform PR commenter
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@master

      - uses: actions/cache@v2
        name: Cache plugin dir
        with:
          path: ~/.tflint.d/plugins
          key: ubuntu-latest-tflint-${{ hashFiles('.tflint.hcl') }}

      - uses: terraform-linters/setup-tflint@v1
        name: Setup TFLint
        with:
          tflint_version: v0.34.1

      - name: tflint
        continue-on-error: true
        run: |
          tflint --init
          cd ${{ github.workspace }}/src/Terraform/key-vault
          tflint -f compact --module

      - name: tfsec
        uses: tfsec/tfsec-pr-commenter-action@main
        with:
          tfsec_args: --soft-fail
          github_token: ${{ github.token }}
          working_directory: ./src/Terraform